[www]
user = php-fpm
group = php-fpm

listen = 9000
listen.owner = php-fpm
listen.group = php-fpm
listen.mode = 0660
listen.allowed_clients = 127.0.0.1

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500
pm.process_idle_timeout = 10s

clear_env = yes
catch_workers_output = yes
decorate_workers_output = no

request_terminate_timeout = 60s
request_slowlog_timeout = 5s
slowlog = /var/log/php85-fpm/slow.log

php_admin_value[error_log] = /var/log/php85-fpm/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path] = /var/lib/php85-fpm/sessions
php_admin_value[open_basedir] = /var/www:/tmp

security.limit_extensions = .php

access.log = /var/log/php85-fpm/access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
